[features]
seeds = false
skip-lint = false

[programs.localnet]
avax_points_exchange = "Hs768q1NX13tbbBHJZrHXEhGtMv666UANzVjy2AakqX1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo \"Add your Anchor tests here\""
