[package]
name = "atx_points_exchange"
version = "0.1.0"
description = "ATX points exchange program built with Anchor."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "atx_points_exchange"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
